{% set version = "4.0.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-wemix
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/WeMix_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/WeMix/WeMix_{{ version }}.tar.gz
  sha256: e738f8e80ec0c18198d7ae513fcce08a32cd3c0a1bce49db5025540baf3e6ffa

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-lme4
    - r-matrix
    - r-matrixstats
    - r-minqa
    - r-npflow
    - r-numderiv
    - r-rmpfr
    - r-statmod
  run:
    - r-base
    - r-lme4
    - r-matrix
    - r-matrixstats
    - r-minqa
    - r-npflow
    - r-numderiv
    - r-rmpfr
    - r-statmod

test:
  commands:
    - $R -e "library('WeMix')"           # [not win]
    - "\"%R%\" -e \"library('WeMix')\""  # [win]

about:
  home: https://american-institutes-for-research.github.io/WeMix/
  dev_url: https://github.com/American-Institutes-for-Research/WeMix/
  license: GPL-2.0-only
  summary: Run mixed-effects models that include weights at every level. The WeMix package fits a weighted mixed model, also known as a multilevel, mixed, or hierarchical linear model (HLM). The weights could be inverse selection probabilities, such as those developed for an education survey where schools are sampled probabilistically,
    and then students inside of those schools are sampled probabilistically. Although mixed-effects models are already available in R, WeMix is unique in implementing methods for mixed models using weights at multiple levels. Both linear and logit models are supported. Models may have up to three levels.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - khusmann
